Try pytest return code checking to fix CI silent failures.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -92,6 +92,13 @@ jobs:
             # https://github.com/illinois-ceesd/mirgecom/issues/212
             for filename in test_*.py ; do
               python -m pytest --durations=10 --tb=native --junitxml=pytest.xml --doctest-modules -rxsw ./"$filename"
+              if [ $? -eq 0 ]
+              then
+                echo "$filename tests succeeded."
+              else
+                echo "$filename tests failed."
+                exit 1
+              fi
             done
 
     examples:
